version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  server:
    build: ./server
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/server
    ports:
      - "3000:3000"
    links:
      - db

  client:
    build: ./client
    command: npm run dev
    # command: /bin/sh -c "npm run build && npm run start"
    tty: true
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
      - /usr/src/client/.next
    ports:
      - 8000:8000
    links:
      - server

volumes:
  node_modules:
  .next: